import { Platform } from "react-native";

const preferredPrimaryFont = "Plus Jakarta Sans";
const preferredSecondaryFont = "Inter";

export const fonts = {
  primary: preferredPrimaryFont,
  secondary: preferredSecondaryFont,
  fallback: Platform.select({
    android: "sans-serif",
    ios: "System",
    default: "System",
  }),
} as const;

export const darkColors = {
  surface: "#051424",
  surfaceDim: "#051424",
  surfaceBright: "#2C3A4C",
  surfaceContainerLowest: "#010F1F",
  surfaceContainerLow: "#0D1C2D",
  surfaceContainer: "#122131",
  surfaceContainerHigh: "#1C2B3C",
  surfaceContainerHighest: "#273647",
  onSurface: "#D4E4FA",
  onSurfaceVariant: "#C8C4D7",
  inverseSurface: "#D4E4FA",
  inverseOnSurface: "#233143",
  outline: "#928EA0",
  outlineVariant: "#474554",
  surfaceTint: "#C6BFFF",
  primary: "#C6BFFF",
  onPrimary: "#2800A0",
  primaryContainer: "#8C80FF",
  onPrimaryContainer: "#22008D",
  inversePrimary: "#5845D9",
  secondary: "#CEBDFF",
  onSecondary: "#381385",
  secondaryContainer: "#4F319C",
  onSecondaryContainer: "#BEA8FF",
  tertiary: "#FFB2BB",
  onTertiary: "#670122",
  tertiaryContainer: "#E7677D",
  onTertiaryContainer: "#5A001C",
  error: "#FFB4AB",
  onError: "#690005",
  errorContainer: "#93000A",
  onErrorContainer: "#FFDAD6",
  background: "#051424",
  onBackground: "#D4E4FA",
  surfaceVariant: "#273647",
  accent: "#FF7A90",
  highlight: "#FFC857",
  success: "#2DD4BF",
  text: "#D4E4FA",
  mutedText: "#928EA0",
} as const;

export const lightColors = {
  surface: "#FFFFFF",
  surfaceDim: "#F0EFEC",
  surfaceBright: "#FFFFFF",
  surfaceContainerLowest: "#FFFFFF",
  surfaceContainerLow: "#F8F7F4",
  surfaceContainer: "#F1F0FA",
  surfaceContainerHigh: "#E9E7F6",
  surfaceContainerHighest: "#E1DFF1",
  onSurface: "#1A1A1A",
  onSurfaceVariant: "#6B7280",
  inverseSurface: "#233143",
  inverseOnSurface: "#F8FAFC",
  outline: "#7D778F",
  outlineVariant: "#D8D4E8",
  surfaceTint: "#5B4CF0",
  primary: "#5B4CF0",
  onPrimary: "#FFFFFF",
  primaryContainer: "#E4DFFF",
  onPrimaryContainer: "#22008D",
  inversePrimary: "#7C6CFF",
  secondary: "#8B5CF6",
  onSecondary: "#FFFFFF",
  secondaryContainer: "#E8DDFF",
  onSecondaryContainer: "#21005E",
  tertiary: "#FF6B6B",
  onTertiary: "#FFFFFF",
  tertiaryContainer: "#FFD9DD",
  onTertiaryContainer: "#5A001C",
  error: "#BA1A1A",
  onError: "#FFFFFF",
  errorContainer: "#FFDAD6",
  onErrorContainer: "#410002",
  background: "#F8F7F4",
  onBackground: "#1A1A1A",
  surfaceVariant: "#ECE8FF",
  accent: "#FF6B6B",
  highlight: "#FFB84D",
  success: "#2DD4BF",
  text: "#1A1A1A",
  mutedText: "#6B7280",
} as const;

export type ThemeColorShape = {
  [Key in keyof typeof darkColors]: string;
};

const withColors = (
  base: ThemeColorShape,
  overrides: Partial<ThemeColorShape>,
): ThemeColorShape => ({
  ...base,
  ...overrides,
});

export const themeNames = [
  "default",
  "dark",
  "cupcake",
  "coffee",
  "luxury",
  "valentine",
  "emerald",
  "corporate",
  "nord",
  "sunset",
] as const;

export const themePalettes = {
  default: darkColors,
  dark: withColors(darkColors, {
    surface: "#0B0B10",
    surfaceDim: "#0B0B10",
    surfaceBright: "#292833",
    surfaceContainerLowest: "#05050A",
    surfaceContainerLow: "#14131B",
    surfaceContainer: "#1B1923",
    surfaceContainerHigh: "#25232F",
    surfaceContainerHighest: "#302E3B",
    onSurface: "#F1EFF8",
    onSurfaceVariant: "#CAC6D4",
    outline: "#9B97A8",
    outlineVariant: "#514E5D",
    surfaceTint: "#C8BFFF",
    primary: "#C8BFFF",
    primaryContainer: "#8B78FF",
    onPrimary: "#24115F",
    background: "#0B0B10",
    onBackground: "#F1EFF8",
    surfaceVariant: "#302E3B",
    text: "#F1EFF8",
    mutedText: "#9B97A8",
  }),
  cupcake: withColors(lightColors, {
    primary: "#D94678",
    primaryContainer: "#F9A8C0",
    onPrimary: "#FFFFFF",
    onPrimaryContainer: "#5F1231",
    secondary: "#8B5CF6",
    secondaryContainer: "#EDE9FE",
    surfaceContainer: "#FFF7FA",
    surfaceContainerHigh: "#FCE7F3",
    surfaceContainerHighest: "#F9D5E5",
    surfaceVariant: "#FCE7F3",
    accent: "#D94678",
    background: "#FFF9FB",
  }),
  coffee: withColors(darkColors, {
    surface: "#211813",
    surfaceDim: "#211813",
    surfaceBright: "#49362B",
    surfaceContainerLowest: "#170F0B",
    surfaceContainerLow: "#2A1E17",
    surfaceContainer: "#33251D",
    surfaceContainerHigh: "#403027",
    surfaceContainerHighest: "#4C3A30",
    onSurface: "#F7E8DA",
    onSurfaceVariant: "#D5BFAE",
    outline: "#AD9180",
    outlineVariant: "#725A4C",
    surfaceTint: "#F0B782",
    primary: "#F0B782",
    primaryContainer: "#C77945",
    onPrimary: "#3B1B08",
    secondary: "#D4A373",
    secondaryContainer: "#6B4935",
    background: "#211813",
    onBackground: "#F7E8DA",
    surfaceVariant: "#4C3A30",
    accent: "#F2CC8F",
    highlight: "#F2CC8F",
    success: "#72C6A1",
    text: "#F7E8DA",
    mutedText: "#AD9180",
  }),
  luxury: withColors(darkColors, {
    surface: "#11100D",
    surfaceDim: "#11100D",
    surfaceBright: "#383329",
    surfaceContainerLowest: "#090806",
    surfaceContainerLow: "#191712",
    surfaceContainer: "#211E18",
    surfaceContainerHigh: "#2C281F",
    surfaceContainerHighest: "#393327",
    onSurface: "#F5EBD2",
    onSurfaceVariant: "#D2C5A8",
    outline: "#A89B80",
    outlineVariant: "#665D4B",
    surfaceTint: "#E2B86A",
    primary: "#E2B86A",
    primaryContainer: "#B98732",
    onPrimary: "#2A1B04",
    secondary: "#DCC38A",
    secondaryContainer: "#68552D",
    background: "#11100D",
    onBackground: "#F5EBD2",
    surfaceVariant: "#393327",
    accent: "#E8C878",
    highlight: "#E8C878",
    success: "#86B89B",
    text: "#F5EBD2",
    mutedText: "#A89B80",
  }),
  valentine: withColors(lightColors, {
    primary: "#DB2777",
    primaryContainer: "#F9A8D4",
    onPrimary: "#FFFFFF",
    onPrimaryContainer: "#640B38",
    secondary: "#E11D48",
    secondaryContainer: "#FFE4E6",
    surfaceContainer: "#FFF1F4",
    surfaceContainerHigh: "#FFE4E9",
    surfaceContainerHighest: "#FECDD3",
    surfaceVariant: "#FFE4E9",
    accent: "#E11D48",
    background: "#FFF8F9",
  }),
  emerald: withColors(lightColors, {
    primary: "#047857",
    primaryContainer: "#6EE7B7",
    onPrimary: "#FFFFFF",
    onPrimaryContainer: "#064E3B",
    secondary: "#0F766E",
    secondaryContainer: "#CCFBF1",
    surfaceContainer: "#F0FDF9",
    surfaceContainerHigh: "#DDF7EE",
    surfaceContainerHighest: "#BDEBDC",
    surfaceVariant: "#DDF7EE",
    accent: "#0F766E",
    background: "#F7FFFC",
    success: "#059669",
  }),
  corporate: withColors(lightColors, {
    primary: "#2563EB",
    primaryContainer: "#93C5FD",
    onPrimary: "#FFFFFF",
    onPrimaryContainer: "#102A56",
    secondary: "#475569",
    secondaryContainer: "#E2E8F0",
    surfaceContainer: "#F4F7FB",
    surfaceContainerHigh: "#E8EEF7",
    surfaceContainerHighest: "#D7E1EF",
    surfaceVariant: "#E8EEF7",
    accent: "#2563EB",
    background: "#F8FAFC",
  }),
  nord: withColors(lightColors, {
    primary: "#5E81AC",
    primaryContainer: "#A3BE8C",
    onPrimary: "#FFFFFF",
    onPrimaryContainer: "#263B2B",
    secondary: "#81A1C1",
    secondaryContainer: "#E5EEF6",
    surfaceContainer: "#F1F5F9",
    surfaceContainerHigh: "#E2E8F0",
    surfaceContainerHighest: "#CBD5E1",
    surfaceVariant: "#E2E8F0",
    accent: "#BF616A",
    background: "#F8FAFC",
    success: "#A3BE8C",
  }),
  sunset: withColors(darkColors, {
    surface: "#1C1420",
    surfaceDim: "#1C1420",
    surfaceBright: "#493047",
    surfaceContainerLowest: "#100B13",
    surfaceContainerLow: "#251A28",
    surfaceContainer: "#30202F",
    surfaceContainerHigh: "#3E2A3B",
    surfaceContainerHighest: "#4B3346",
    onSurface: "#FFE9DC",
    onSurfaceVariant: "#E6C5BC",
    outline: "#B99597",
    outlineVariant: "#785D68",
    surfaceTint: "#FFB38A",
    primary: "#FF9B71",
    primaryContainer: "#E76F51",
    onPrimary: "#431306",
    secondary: "#F2A6B3",
    secondaryContainer: "#754052",
    background: "#1C1420",
    onBackground: "#FFE9DC",
    surfaceVariant: "#4B3346",
    accent: "#F2A6B3",
    highlight: "#FFD166",
    success: "#7DCFB6",
    text: "#FFE9DC",
    mutedText: "#B99597",
  }),
} as const;

export const themes = Object.fromEntries(
  themeNames.map((name) => [name, { mode: name, name, colors: themePalettes[name] }]),
) as {
  [Name in (typeof themeNames)[number]]: {
    mode: Name;
    name: Name;
    colors: ThemeColorShape;
  };
};

export const colors = darkColors;

export const typography = {
  displayLg: {
    fontFamily: fonts.fallback,
    fontSize: 48,
    fontWeight: "700",
    lineHeight: 56,
    letterSpacing: 0,
  },
  headlineLg: {
    fontFamily: fonts.fallback,
    fontSize: 32,
    fontWeight: "600",
    lineHeight: 40,
    letterSpacing: 0,
  },
  headlineLgMobile: {
    fontFamily: fonts.fallback,
    fontSize: 24,
    fontWeight: "600",
    lineHeight: 32,
    letterSpacing: 0,
  },
  titleMd: {
    fontFamily: fonts.fallback,
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 28,
    letterSpacing: 0,
  },
  bodyLg: {
    fontFamily: fonts.fallback,
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 24,
    letterSpacing: 0,
  },
  bodySm: {
    fontFamily: fonts.fallback,
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 20,
    letterSpacing: 0,
  },
  labelMd: {
    fontFamily: fonts.fallback,
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 16,
    letterSpacing: 0.6,
  },
} as const;

export const spacing = {
  unit: 4,
  xs: 8,
  sm: 16,
  md: 24,
  lg: 32,
  xl: 48,
  gutter: 24,
  marginMobile: 16,
  marginDesktop: 40,
} as const;

export const radius = {
  sm: 4,
  default: 8,
  md: 12,
  lg: 16,
  xl: 24,
  full: 9999,
} as const;

export const componentTypography = {
  splashWordmark: {
    ...typography.displayLg,
    fontSize: 58,
    fontWeight: "800",
    lineHeight: 66,
  },
  splashTagline: {
    ...typography.labelMd,
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 18,
    letterSpacing: 7,
  },
  splashStatus: {
    ...typography.bodySm,
    fontSize: 15,
    fontWeight: "500",
    lineHeight: 28,
    letterSpacing: 1.4,
  },
} as const;

export const splash = {
  background: {
    top: "#071225",
    middle: "#111A32",
    lower: "#071424",
    bottom: "#031322",
  },
  glow: {
    primary: darkColors.primaryContainer,
    secondary: "#5A4E8D",
    base: darkColors.background,
  },
  logoShadow: darkColors.primaryContainer,
  progressTrack: "rgba(162, 166, 210, 0.52)",
  statusText: "rgba(156, 148, 181, 0.58)",
  tagline: "#9C96BE",
  wordmark: "#D8D3F2",
} as const;

export const elevation = {
  level0: {
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  level1: {
    shadowColor: "rgba(11, 16, 32, 0.4)",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  level2: {
    shadowColor: "rgba(91, 76, 240, 0.34)",
    shadowOpacity: 0.24,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  level3: {
    shadowColor: "rgba(11, 16, 32, 0.48)",
    shadowOpacity: 0.32,
    shadowRadius: 32,
    shadowOffset: { width: 0, height: 12 },
    elevation: 16,
  },
} as const;

export const design = {
  componentTypography,
  colors,
  darkColors,
  elevation,
  fonts,
  lightColors,
  radius,
  spacing,
  splash,
  themes,
  typography,
} as const;
